import numpy as np
from numpy import *
import matplotlib.pyplot as plt

A = np.array([[4,5],[1,2]])
B = np.array([20,13])
answer = np.linalg.solve(A,B)
print(answer)

'''
***************** Code for plotting the graph **********************
This code first initializes all th evalues for x
Then, an equation in y is given
In the y equation, an array is generated by running a for loop
The for loop assigns the value for x while running through the list of x
Then the values are taken for y and a list is generated for y

*********************************************************************
'''
x1 = np.arange(20)

y1 = [(20-5*i)/4 for i in x1]

x2 = np.arange(20)

y2 = [(13-2*j) for j in x2]

plt.plot(x1,y1,label='First line',color='r')
plt.plot(x2,y2,label='Second line',color='b')

plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.legend()
plt.grid()
plt.show()
